// OSD strings. The System Configuration screen re-localises live while the Language value is changed
// (title, item names, header, hints), as the real console does.
export const LANG_NAMES = ['English', 'French', 'Spanish', 'German', 'Italian', 'Dutch', 'Portuguese'];
export const STRINGS = {
  English:    { title: 'System Configuration', items: ['Clock Adjustment', 'Screen Size', 'Digital Out (Optical)', 'Component Video Out', 'Remote Control', 'Language'], display: 'Display', enter: 'Enter', back: 'Back', options: 'Options', langs: ['English', 'French', 'Spanish', 'German', 'Italian', 'Dutch', 'Portuguese'] },
  French:     { title: 'Configuration du Système', items: ['Réglage de l\'horloge', 'Taille de l\'écran', 'Sortie numérique (optique)', 'Sortie vidéo composante', 'Télécommande', 'Langue'], display: 'Affichage', enter: 'Entrer', back: 'Précédent', options: 'Options', langs: ['Anglais', 'Français', 'Espagnol', 'Allemand', 'Italien', 'Néerlandais', 'Portugais'] },
  Spanish:    { title: 'Configuración del Sistema', items: ['Ajuste del reloj', 'Tamaño de pantalla', 'Salida digital (óptica)', 'Salida de vídeo por componentes', 'Mando a distancia', 'Idioma'], display: 'Visualizar', enter: 'Aceptar', back: 'Atrás', options: 'Opciones', langs: ['Inglés', 'Francés', 'Español', 'Alemán', 'Italiano', 'Holandés', 'Portugués'] },
  German:     { title: 'Systemkonfiguration', items: ['Uhr einstellen', 'Bildschirmgröße', 'Digitalausgang (optisch)', 'Component-Videoausgang', 'Fernbedienung', 'Sprache'], display: 'Anzeige', enter: 'Eingabe', back: 'Zurück', options: 'Optionen', langs: ['Englisch', 'Französisch', 'Spanisch', 'Deutsch', 'Italienisch', 'Niederländisch', 'Portugiesisch'] },
  Italian:    { title: 'Configurazione di Sistema', items: ['Regolazione orologio', 'Dimensione schermo', 'Uscita digitale (ottica)', 'Uscita video component', 'Telecomando', 'Lingua'], display: 'Visualizzazione', enter: 'Invio', back: 'Indietro', options: 'Opzioni', langs: ['Inglese', 'Francese', 'Spagnolo', 'Tedesco', 'Italiano', 'Olandese', 'Portoghese'] },
  Dutch:      { title: 'Systeemconfiguratie', items: ['Klok instellen', 'Schermformaat', 'Digitale uitgang (optisch)', 'Component video-uitgang', 'Afstandsbediening', 'Taal'], display: 'Weergave', enter: 'Bevestigen', back: 'Terug', options: 'Opties', langs: ['Engels', 'Frans', 'Spaans', 'Duits', 'Italiaans', 'Nederlands', 'Portugees'] },
  Portuguese: { title: 'Configuração do Sistema', items: ['Acerto do relógio', 'Tamanho do ecrã', 'Saída digital (óptica)', 'Saída de vídeo componente', 'Controlo remoto', 'Idioma'], display: 'Visualizar', enter: 'Confirmar', back: 'Retroceder', options: 'Opções', langs: ['Inglês', 'Francês', 'Espanhol', 'Alemão', 'Italiano', 'Holandês', 'Português'] },
};
export function tr(lang) { return STRINGS[lang] || STRINGS.English; }
